[server]
port=9000

[mongo]
connection_string="mongodb://localhost:27017"
username="root"
password="root"
overseer_db="overseer"
overseer_recordings_collection="overseer_recordings"


[amqp]
host="localhost"
port="5672"
username="guest"
password="guest"
vhost="/"
recordings_exchange="recordings"
recordings_exchange_type="topic"
recordings_route="new"
recordings_new_queue="recordings_new"
recordings_new_queue_type="quorum"
