version: '3.3'

services:
  mongo:
    image: mongo:5.0.12
    container_name: 'overseer_mongo'
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - overseer_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'overseer_rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - overseer_net

  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile

    container_name: 'overseer_api'
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - OVERSEER_API_CONFIG_PATH
    ports:
      - "9000:9000"
    networks:
      - overseer_net
    depends_on:
      - mongo
      - rabbitmq
  model:
    image: overseer_model
    container_name: 'overseer_model'
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - OVERSEER_API_CONFIG_PATH
    networks:
      - overseer_net
    depends_on:
      - mongo
      - rabbitmq

  metabase:
    image: maczomen/overseer_metabase
    container_name: 'overseer_metabase'
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - overseer_net

networks:
  overseer_net:
    driver: bridge
  metanet1-secrets:
    driver: bridge
secrets:
   db_password:
     file: metabase/db_password.txt
   db_user:
     file: metabase/db_user.txt
