version: '3.3'

services:
  mongo:
    image: mongo:5.0.12
    container_name: 'overseer_mongo'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - overseer_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'overseer_rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - overseer_net

  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile

    container_name: 'overseer_api'
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - OVERSEER_API_CONFIG_PATH
    ports:
      - "9000:9000"
    networks:
      - overseer_net
    depends_on:
      - mongo
      - rabbitmq
  model:
    image: overseer_model
    container_name: 'overseer_model'
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - OVERSEER_API_CONFIG_PATH
    networks:
      - overseer_net
    depends_on:
      - mongo
      - rabbitmq
  metabase:
    image: metabase/metabase:v0.44.3
    container_name: meatabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
    - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
    networks:
      - metanet1-secrets
    depends_on:
      - postgres
    secrets:
      - db_password
      - db_user
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - metanet1-secrets
    secrets:
      - db_password
      - db_user

networks:
  overseer_net:
    driver: bridge
  metanet1-secrets:
    driver: bridge
secrets:
   db_password:
     file: metabase/db_password.txt
   db_user:
     file: metabase/db_user.txt
