version: '3.3'

services:
  mongo:
    image: mongo
    container_name: 'overseer_mongo'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'overseer_rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
