name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: docker build . --file Dockerfile --tag overseer_api:latest && docker push bartoszdab/overseer_api:latest
